name: bayes_toolbox
channels:
  - conda-forge
  - defaults
dependencies:
  - aeppl=0.0.38=pyhd8ed1ab_0
  - aeppl-base=0.0.38=pyhd8ed1ab_0
  - aesara=2.8.7=py311h1d45e85_1
  - aesara-base=2.8.7=py311h6eed73b_1
  - anyio=3.6.2=pyhd8ed1ab_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311h5547dcb_3
  - arviz=0.13.0=pyhd8ed1ab_1
  - asttokens=2.1.0=pyhd8ed1ab_0
  - atk-1.0=2.38.0=h1d18e73_1
  - attrs=22.1.0=pyh71513ae_1
  - babel=2.11.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - blas=2.116=openblas
  - blas-devel=3.9.0=16_osx64_openblas
  - bleach=5.0.1=pyhd8ed1ab_0
  - brotli=1.0.9=hb7f2c08_8
  - brotli-bin=1.0.9=hb7f2c08_8
  - brotlipy=0.7.0=py311h5547dcb_1005
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.18.1=h0d85af4_0
  - c-compiler=1.5.1=hbf74d83_0
  - ca-certificates=2023.08.22=hecd8cb5_0
  - cachetools=5.2.0=pyhd8ed1ab_0
  - cairo=1.16.0=h904041c_1014
  - cctools=973.0.1=h76f1dac_10
  - cctools_osx-64=973.0.1=h2b95895_10
  - certifi=2023.7.22=py311hecd8cb5_0
  - cffi=1.15.1=py311ha86e640_2
  - cftime=1.6.2=py311hd5badaa_1
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - clang=14.0.6=h694c41f_0
  - clang-14=14.0.6=default_h55ffa42_0
  - clang_osx-64=14.0.6=h3113cd8_3
  - clangxx=14.0.6=default_h55ffa42_0
  - clangxx_osx-64=14.0.6=h6f97653_3
  - cloudpickle=2.2.0=pyhd8ed1ab_0
  - compiler-rt=14.0.6=h613da45_0
  - compiler-rt_osx-64=14.0.6=hab78ec2_0
  - cons=0.4.5=pyhd8ed1ab_0
  - contourpy=1.0.6=py311hd2070f0_0
  - cryptography=38.0.3=py311h61927ef_0
  - curl=7.86.0=h581aaea_1
  - cxx-compiler=1.5.1=hb8565cd_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.3=py311h814d153_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - etuples=0.3.8=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hcec6c5f_0
  - fastprogress=1.0.3=pyhd8ed1ab_0
  - filelock=3.8.0=pyhd8ed1ab_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=hb0a0c50_2
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py311h5547dcb_1
  - freetype=2.12.1=h3f81eb7_0
  - fribidi=1.0.10=haf1e3a3_0
  - gdk-pixbuf=2.42.8=h3648f77_1
  - gettext=0.21.1=h8a4c099_0
  - giflib=5.2.1=hbcb3906_2
  - graphite2=1.3.14=he9d5cce_1
  - graphviz=6.0.1=ha8464fc_0
  - gtk2=2.24.33=h7c1209e_2
  - gts=0.7.6=hccb3bdf_2
  - harfbuzz=5.3.0=h08f8713_0
  - hdf4=4.2.15=h7aa5921_5
  - hdf5=1.12.2=nompi_h1f71328_100
  - icu=70.1=h96cf925_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=5.0.0=pyha770c72_1
  - importlib_resources=5.10.0=pyhd8ed1ab_0
  - ipykernel=6.17.1=pyh736e0ef_0
  - ipython=8.6.0=pyhd1c38e8_1
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=hac89ed1_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.17.0=pyhd8ed1ab_0
  - jupyter_client=7.4.5=pyhd8ed1ab_0
  - jupyter_core=5.0.0=py311h6eed73b_0
  - jupyter_server=1.23.1=pyhd8ed1ab_0
  - jupyterlab=3.5.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.16.3=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py311hd2070f0_1
  - krb5=1.19.3=hb98e516_0
  - lcms2=2.14=h90f4b2a_0
  - ld64=609=hc6ad406_10
  - ld64_osx-64=609=h1e06c2b_10
  - lerc=4.0.0=hb486fe8_0
  - libblas=3.9.0=16_osx64_openblas
  - libbrotlicommon=1.0.9=hb7f2c08_8
  - libbrotlidec=1.0.9=hb7f2c08_8
  - libbrotlienc=1.0.9=hb7f2c08_8
  - libcblas=3.9.0=16_osx64_openblas
  - libclang-cpp14=14.0.6=default_h55ffa42_0
  - libcurl=7.86.0=h581aaea_1
  - libcxx=14.0.6=hccf4f1f_0
  - libdeflate=1.14=hb7f2c08_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.4.2=h0d85af4_5
  - libgd=2.3.3=he7e2580_1
  - libgfortran=5.0.0=9_5_0_h97931a8_26
  - libgfortran5=11.3.0=h082f757_26
  - libglib=2.74.1=h4c723e1_1
  - libiconv=1.17=hac89ed1_0
  - liblapack=3.9.0=16_osx64_openblas
  - liblapacke=3.9.0=16_osx64_openblas
  - libllvm14=14.0.6=h5b596cc_1
  - libnetcdf=4.8.1=nompi_hc61b76e_106
  - libnghttp2=1.47.0=h5aae05b_1
  - libopenblas=0.3.21=openmp_h429af6e_3
  - libpng=1.6.38=ha978bb4_0
  - librsvg=2.54.4=h3d48ba6_0
  - libsodium=1.0.18=hbcb3906_1
  - libsqlite=3.39.4=ha978bb4_0
  - libssh2=1.10.0=h47af595_3
  - libtiff=4.4.0=hdb44e8a_4
  - libtool=2.4.6=hcec6c5f_1009
  - libwebp=1.2.4=hfa4350a_0
  - libwebp-base=1.2.4=h775f41a_0
  - libxcb=1.13=h0d85af4_1004
  - libxml2=2.10.3=hb9e07b5_0
  - libzip=1.9.2=h6db710c_1
  - libzlib=1.2.13=hfd90126_4
  - llvm-openmp=15.0.4=h61d9ccf_0
  - llvm-tools=14.0.6=h5b596cc_1
  - logical-unification=0.4.5=pyhd8ed1ab_0
  - markupsafe=2.1.1=py311h5547dcb_2
  - matplotlib-base=3.6.2=py311h2bf763f_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - minikanren=1.0.3=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - mkl=2022.1.0=h860c996_928
  - mkl-service=2.4.0=py311h552c0e0_0
  - multipledispatch=0.6.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.4.8=pyhd8ed1ab_0
  - nbclient=0.7.0=pyhd8ed1ab_0
  - nbconvert=7.2.4=pyhd8ed1ab_0
  - nbconvert-core=7.2.4=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.4=pyhd8ed1ab_0
  - nbformat=5.7.0=pyhd8ed1ab_0
  - ncurses=6.3=h96cf925_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - netcdf4=1.6.1=nompi_py311h41bc3eb_101
  - notebook=6.5.2=pyha770c72_1
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - numpy=1.23.4=py311h62c7003_1
  - openblas=0.3.21=openmp_hbefa662_3
  - openjpeg=2.5.0=h5d0d7b0_1
  - openssl=3.0.11=hca72f7f_2
  - packaging=23.1=py311hecd8cb5_0
  - pandas=1.5.1=py311hd84f3f5_1
  - pandoc=2.19.2=h694c41f_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.11=h7fca291_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.3=py311hecd8cb5_0
  - pcre2=10.40=h1c4e4bc_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py311he7df5c9_3
  - pip=22.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h9ed2024_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.5.2=pyhd8ed1ab_1
  - prometheus_client=0.15.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.32=pyha770c72_0
  - psutil=5.9.4=py311h5547dcb_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pymc=4.3.0=hd8ed1ab_0
  - pymc-base=4.3.0=pyhd8ed1ab_0
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.19.2=py311h5547dcb_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.0=h559f36b_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-graphviz=0.20.1=pyh22cad53_0
  - python_abi=3.11=2_cp311
  - pytz=2022.6=pyhd8ed1ab_0
  - pyzmq=24.0.1=py311habfacb3_1
  - readline=8.1.2=h3899abd_0
  - requests=2.28.1=pyhd8ed1ab_1
  - scipy=1.9.3=py311h939689b_2
  - seaborn=0.12.1=hd8ed1ab_0
  - seaborn-base=0.12.1=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.5.1=pyhd8ed1ab_0
  - sigtool=0.1.3=h88f4db0_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - stack_data=0.6.0=pyhd8ed1ab_0
  - statsmodels=0.13.5=py311hd5badaa_2
  - tapi=1100.0.11=h9ce4665_0
  - tbb=2021.6.0=hb8565cd_1
  - terminado=0.17.0=pyhd1c38e8_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py311h5547dcb_1
  - traitlets=5.5.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022f=h191b570_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.2=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xarray=2022.11.0=pyhd8ed1ab_0
  - xarray-einstats=0.3.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h35c211d_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xz=5.2.6=h775f41a_0
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.10.0=pyhd8ed1ab_0
  - zlib=1.2.13=hfd90126_4
  - zstd=1.5.2=hfa58983_4
  - pip:
    - bayes-toolbox==0.1.0
    - black==23.3.0
    - build==0.10.0
    - causalgraphicalmodels==0.0.4
    - click==8.1.3
    - colorama==0.4.6
    - coverage==7.3.2
    - docopt==0.6.2
    - docutils==0.19
    - ghp-import==2.1.0
    - griffe==0.36.7
    - iniconfig==2.0.0
    - jaraco-classes==3.2.3
    - keyring==23.13.1
    - markdown==3.3.7
    - markdown-it-py==2.2.0
    - mdurl==0.1.2
    - mergedeep==1.3.4
    - mkdocs==1.5.3
    - mkdocs-autorefs==0.5.0
    - mkdocs-material==9.4.6
    - mkdocs-material-extensions==1.3
    - mkdocstrings==0.23.0
    - mkdocstrings-python==1.7.3
    - more-itertools==9.1.0
    - mypy-extensions==1.0.0
    - networkx==3.1
    - paginate==0.5.6
    - pathspec==0.11.1
    - pipreqs==0.4.13
    - pkginfo==1.9.6
    - pluggy==1.0.0
    - pygments==2.16.1
    - pymdown-extensions==10.3
    - pyproject-hooks==1.0.0
    - pytest==7.3.1
    - pyyaml==6.0
    - pyyaml-env-tag==0.1
    - readme-renderer==37.3
    - regex==2023.10.3
    - requests-toolbelt==0.10.1
    - rfc3986==2.0.0
    - rich==13.3.4
    - tokenize-rt==5.0.0
    - twine==4.0.2
    - watchdog==2.3.1
    - watermark==2.3.1
    - yarg==0.1.9
prefix: /Users/hyosubkim/opt/anaconda3/envs/bayes_toolbox
