site_name: bayesian-statistics-toolbox
site_url: https://example.com/
nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - Tutorials: tutorials.md
    - Future Plans: future-plans.md
    - How to Contribute: how-to-contribute.md
    - to delete: to-delete.md
theme: readthedocs
